baseURL = "https://atlili.github.io/MySiteWeb/"
languageCode = "en-us"
title = "Initio - Free"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Amal Tlili"
    description = "A mystery person"
    email = "amal.tlili04@gmail.com"
    address = "Sokra, Ariana, Tunisie"
    year = 2018
    avatar = "images/amal2.png"
    background = ""
    favicon = "images/amal2.png"
    DateForm = "December 6, 2018"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/amal.tlili.524"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/tlili9619"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/107992645194258171307"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/amal-tlili-a9b473172/"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/atlili"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "amal.tlili04@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
